services:
  backend:
    container_name: backend
    build: docker/backend/
    restart: unless-stopped
    volumes:
      - .:/app

  nginx:
    container_name: nginx
    build: docker/nginx/
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/app
    depends_on:
      - backend
