[game]
# Everything will be calculated of the world size.

world_size = [16.0, 9.0]                        # World size in units (X, Y)

    [game.paddle]
        size = [0.2, 2.5]              # X and Y size of the paddle in units
        x_offset = 0.0                 # Distance from the paddle to the edge of the screen
        speed = 6.5                  # Paddle speed in units per second
        center_of_mass = [0.75, 1.0]   # Used to calculate the ball's bounce angle. Height = Paddle's height / 2, Width = bounce angle when hitting the paddle's edge
        
    [game.ball]
        speed = 8.0                      # Ball speed in units per second
        speed_multiplier = 0.3        # Increase ball speed after each second for a fraction of the base speed
        size = 0.2

[match]

score_limit = 11            # Score limit for a match
tick_rate = 60              # Tick rate in Hz (updates per second)

max_reconnections = 3       # Maximum number of reconnections allowed before a match is considered lost

match_start_timer = 3       # Time in seconds until the match starts after all players are connected
match_connect_timeout = 10  # Time in seconds until every player has to be connected
reconnect_timeout = 10      # Time in seconds until a user must reconnect after a disconnect before the match is lost

[tournament]

time_between_matches = 5    # Seconds between matches in a tournament
min_players = 2             # Minimum number of players required to start a tournament
max_players = 12            # Maximum number of players allowed in a tournament